import type { Scenario } from './types';
import { DEFAULT_PARAMS } from '../data/defaults';

export const SCENARIOS: Scenario[] = [
  {
    key: 'conservative',
    label: 'Conservative — Back-end infrastructure only',
    labelJa: '保守的：バックエンドインフラのみ',
    description: 'B2B adoption progresses modestly. Stablecoins remain mostly invisible financial infrastructure.',
    params: {
      ...DEFAULT_PARAMS,
      crossBorderAdoptionRate: 0.03,
      corporateBalanceRatio: 0.05,
      b2bReuseRate: 0.08,
      scPayrollAdoptionRate: 0.005,
      agentUserGrowthRate: 0.12,
      agentWalletOpenRate: 0.02,
      issuerIncentiveIntensity: 0.2,
      merchantAdoptionSubsidy: 0.2,
      exchangeHoldingReward: 0.005,
      cardCashbackRate: 0.003,
      regulatoryFriction: 0.7,
      uxFriction: 0.8,
      brandTrust: 0.3,
    },
  },
  {
    key: 'base',
    label: 'Base — Gradual spillover',
    labelJa: 'ベースライン：段階的スピルオーバー',
    description: 'B2B adoption grows steadily. AI-agent wallets gradually introduce individuals to stablecoin balances.',
    params: { ...DEFAULT_PARAMS },
  },
  {
    key: 'bull',
    label: 'Bull — Branded JPY flywheel',
    labelJa: 'ブル：ブランドJPYフライホイール',
    description: 'Aggressive incentive programs. By 2037, a branded JPY-like balance emerges as mainstream.',
    params: {
      ...DEFAULT_PARAMS,
      crossBorderAdoptionRate: 0.12,
      corporateBalanceRatio: 0.15,
      b2bReuseRate: 0.30,
      scPayrollAdoptionRate: 0.05,
      payrollScShare: 0.12,
      treasuryRetentionBias: 0.75,
      agentUserGrowthRate: 0.35,
      agentWalletOpenRate: 0.12,
      stablecoinTopupRate: 0.35,
      issuerIncentiveIntensity: 0.85,
      merchantAdoptionSubsidy: 0.85,
      exchangeHoldingReward: 0.030,
      lendingCampaignApy: 0.055,
      cardCashbackRate: 0.025,
      merchantDiscountRate: 0.015,
      regulatoryFriction: 0.25,
      uxFriction: 0.35,
      brandTrust: 0.80,
      consumerProtectionQuality: 0.75,
    },
  },
];
